### ISSUE TITLE
add "let's encrypt" support to auto provision FQDN cert for external traffic

### ISSUE THREAD

**Issue by wenchenglu** [istio/old_auth_repo#140]
we may consider supporting "let's encrypt" to auto provision FQDN cert to support end user traffic, or peer service that doesn't run istio proxy and doesn't support spiffe.

**Comment by fotinakis** [comment]
Yes please!

**Comment by borancar** [comment]
Can someone move this issue onto the new repo, the same that was done for https://github.com/istio/old_pilot_repo/issues/484?

**Comment by ldemailly** [comment]
closing this in favor of istio/istio#2310 (though we lose the 26 +1  this one got)
