### ISSUE TITLE
e2e test for node agent

### ISSUE THREAD

**Issue by myidpt** [istio/old_auth_repo#305]
Our current e2e test only tests CA, we need it to test the key/cert provision on node agent as well.

**Comment by ldemailly** [comment]
also 1/2h maybe short for outages
I think the validity of the agent-CA cert should be higher

**Comment by mangchiandjjoe** [comment]
start working on it

**Comment by wattli** [comment]
I will add something for GCE support as well.

**Comment by myidpt** [comment]
The onpreme node agent e2e test is done by https://github.com/istio/istio/pull/1560. keep this bug open for GCE node agent e2e test.
